/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package util;

/**
 *
 * @author erick.araujo
 */
/** * This class is generated by the Netbeans IDE, 
 * and registers all REST root resources created in the project. 
 * Please, DO NOT EDIT this class ! */
@javax.ws.rs.ApplicationPath("/resources")
public class ApplicationConfig extends javax.ws.rs.core.Application {}